services:
  postgres:
    image: 'postgis/postgis:15-3.3'
    container_name: postgres-container
    environment:
      - POSTGRES_DB=mydatabase
      - POSTGRES_USER=myuser
      - POSTGRES_PASSWORD=0112
    volumes:
      - ./postgre_db:/var/lib/postgresql/data
    ports:
      - '5432:5432'
